name: feeds-manager
on: push
jobs:
  app_test:
    name: App Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
        id: go
      - name: Check out code
        uses: actions/checkout@v2
      - name: Cache dependenies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-message-relayer-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-message-relayer
      - name: Run Linter
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.45.2

          # Optional: working directory, useful for monorepos
          working-directory: src

          # Optional: golangci-lint command line arguments.
          args: --timeout=2m0s
      - name: Run Test Suite
        run: go test ./src/...
